[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm ci && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  # Variables de entorno para producción
  VITE_APP_MODE = "production"
  VITE_USE_MOCK_API = "true"

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"