# Configuraci贸n de build para Netlify
[build]
  # Directorio base donde se encuentra el c贸digo del frontend
  base = "frontend"
  # Comando para construir el sitio
  command = "npm run build"
  # Directorio de publicaci贸n (relativo al directorio base)
  publish = "dist"

# Regla de redirecci贸n para Single Page Applications (SPA)
# Esto asegura que todas las rutas sean manejadas por index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

